---
title: "PoCS Assignment 1"
author: "P. Alexander Burnham"
date: "September 4, 2018"
output: pdf_document
---


**#1)**

*Assumptions (including the information from assumptions a, b and f):*

$D_f \propto V^2l^2$  (assumption c)

$P \propto D_fV$  (assumption d)

$N \propto l^3$  (assumption e)

$P \propto N$  (assumption g)

*Operation:*

1) Substitute $D_f \propto V^2l^2$ into $P \propto D_fV$ then substitute $P$ for $l^3$ using assumptions g and e:

$$l^3 \propto V^3l^2$$  

2) Divide $l^3$ by $l^2$, rearrange assumption e ($l \propto N^{1/3}$) and substitute in after division: 

 $$l^3/l^2 \propto (V^3l^2)/l^2$$ 

$$N^{1/3} \propto V^3$$

3) Take the cube root of both sides and simplify: 

 $$\sqrt[3]{N^{1/3}} \propto \sqrt[3]{(V^3}$$  

 $$V \propto N^{1/9}$$ 

**#2)**
1/9 roughly equates to a slope of 0.111. After importing the current times for the 2000m (http://www.worldrowing.com/events/statistics/) and fitting a linear model as done in the McMahon and Bonner paper, we see a similar trend with a slope of 0.166. This is a slightly steeper slope but based on the coarseness of the data and the limited range of the variables in terms of orders of magnitude, they can be considered to be very similar. This slight increase, if more than a product of the limited data, might be due to technological advancements that allow for the reduction of friction in larger hulled boats. A premise (at least of sailing) is that larger boats go faster all else being equal so technological advancement might have strengthened this relationship.


```{r, echo=FALSE}
###################################################################
# PoCS Assignment 1 code
# P. Alexander Burnham
# Sept 5, 2018
###################################################################

#Preliminaries:
# Clear memory of characters
ls()
rm(list=ls())


# set working Directory:
setwd("~/Documents/GitHub/BurnhamPoCS")

# Read in Data:
rowing <- read.csv("assignment1_rowing.csv", 
                header=TRUE, 
                sep = ",", 
                stringsAsFactors = FALSE)

# convert time into seconds
rowing$seconds <- as.numeric(strptime(rowing$Time, format="%M:%S") - as.POSIXct(format(Sys.Date())), units="secs")

# convert to meters per second
rowing$MperSec <- 2000/rowing$seconds

# model fitting line to data set
mod <- lm(rowing$MperSec~rowing$Class)

# plot speed by number of oarsman 
plot(rowing$Class, rowing$MperSec, xlab="Number of Oarsman", ylab="speed (m/s)", main = "Modern World Records for the 2000m by Class")
abline(mod, col = "red")

summary(mod) # print model


```


**#3)**
