---
title: "PoCS Assignment 4"
author: "P. Alexander Burnham"
date: "September 25, 2018"
output: pdf_document
---
PoCS Assignment github repo: https://github.com/alexburn17/BurnhamPoCS


Worked with: 



**Problem 1:**

```{r, echo=FALSE, message=FALSE}

# START FUNCTION ###########################################################################

SimonMod <- function(p=0.01, bag=bagVec, runTime=100){

vec <- bag[runif(n=1, 1, length(bag))]
  
for(i in 1:runTime){

  pact <- runif(1)
  
  if(pact<=p){ 
    vec[i] <- bag[runif(n=1, 1, length(bag))]}
  
  if(pact>p){ 
    vec[i] <- vec[runif(n=1, 1, length(vec))]}
}
  return(vec)
}

# END FUNCTION #############################################################################



par(mfrow=c(1,3))

bagVec <- c(0:1000000)

# p=0.1
SimonVec.1 <- SimonMod(p=0.1, bag=bagVec, runTime=1000000)

x <- as.data.frame(table(SimonVec.1))
x$Freq<- log10(x$Freq)
x <- x[order(x$Freq, decreasing = T),] 

mod <- lm(x$Freq~log10(1:length(x$Freq)))

plot(y=x$Freq, x=log10(1:length(x$Freq)), main="Simon Zipf plot (p=0.1)", 
     ylab="log10(Frequency)", xlab = "log10(Rank)")
abline(mod, col="green")
text(x=1,y=4, paste("slope=",round(mod$coefficients[2], 3)))


# p=0.01
SimonVec.01 <- SimonMod(p=0.01, bag=bagVec, runTime=1000000)

x1 <- as.data.frame(table(SimonVec.01))
x1$Freq<- log10(x1$Freq)
x1 <- x1[order(x1$Freq, decreasing = T),] 

mod1 <- lm(x1$Freq~log10(1:length(x1$Freq)))

plot(y=x1$Freq, x=log10(1:length(x1$Freq)), main="Simon Zipf plot (p=0.01)", 
     ylab="log10(Frequency)", xlab = "log10(Rank)")
abline(mod1, col="red")
text(x=1,y=4, paste("slope=",round(mod1$coefficients[2], 3)))

# p=0.001
SimonVec.001 <- SimonMod(p=0.001, bag=bagVec, runTime=10000000)

x2 <- as.data.frame(table(SimonVec.001))
x2$Freq<- log10(x2$Freq)
x2 <- x2[order(x2$Freq, decreasing = T),] 

mod2 <- lm(x2$Freq~log10(1:length(x2$Freq)))

plot(y=x2$Freq, x=log10(1:length(x2$Freq)), main="Simon Zipf plot (p=0.001)", 
     ylab="log10(Frequency)", xlab = "log10(Rank)")
abline(mod2, col="blue")
text(x=1,y=4, paste("slope=",round(mod2$coefficients[2], 3)))

par(mfrow=c(1,1))



```



**Problem 3:**

**Problem 4:**
**a)**
**b)**
```{r, echo=FALSE, message=FALSE}


setwd("~/Documents/GitHub/BurnhamPoCS")

# Read in Data:
book <- read.csv("book.csv", 
                header=TRUE, 
                stringsAsFactors = FALSE)
x3 <- log10(book$X41)

x3 <- x3[order(x3, decreasing = T)]

mod3 <- lm(x3~log10(1:length(x3)))

plot(x3, x=log10(1:length(x3)), main = "Zipf Plot of Ulysses", ylab="log10(Frequency)", xlab="log10(Rank)")

abline(mod3, col="red")
text(x=3, y=3.5, paste("The slope is -1.012"))


```
**c)**

Trim to find more accurate scaling:
```{r, echo=FALSE, message=FALSE}




x4 <- x3[x3<2.9 & x3 > 1]

mod4 <- lm(x4~log10(1:length(x4)))

plot(x4, x=log10(1:length(x4)), main = "Zipf Plot of Ulysses", ylab="log10(Frequency)", xlab="log10(Rank)", xlim=c(1.5,3.5))

abline(mod4, col="red")
text(x=3, y=2.5, paste("a = 0.8715"))
text(x=3, y=2.1, paste("p = 0.1285"))

#alpha = 1 - p

#0.8715 = 1 - p
```

**Problem 6:**

**a)**
```{r, echo=FALSE, message=FALSE}

library("poweRlaw")

N=c(1, 10^2, 10^3, 10^4, 10^5, 10^6) 
k=(1:1000)


#mat <- matrix(nrow = 1000, ncol = 6)

#for(n in 1:6){
#  for(i in 1:1000){
#    mat[i, n] <- max(rpldis(n=N[n], xmin=1, alpha=5/2, discrete_max = 1000))
#}
#}


#matDat <- as.data.frame(mat)
#CD.sorted <- apply(matDat, 2, sort, decreasing=T)

setwd("~/Documents/GitHub/BurnhamPoCS")

# Read in Data:
mat <- read.csv("NKsorted.csv", 
                header=TRUE, 
                stringsAsFactors = FALSE)

mat2 <- as.matrix(mat)

matplot(log10(mat2), type="o", cex=.2, main="K_max by N", xlab = "Rank", ylab="log10(k_max)", col=c(1:6))
legend("topright", inset=0.01, legend=c("10^1","10^2","10^3","10^4","10^5","10^6"), col=c(1:6), pch=15)

```

**b)**

```{r, echo=FALSE, message=FALSE}
par(mfrow=c(1,2))

kmeanEst <- colMeans(mat2)
mod5 <- lm(log10(kmeanEst)~log10(N)) 
plot(y=log10(kmeanEst), x=log10(N), main="K_max estimate by N", xlab = "log10(mean(k_max))", ylab = "log10(N)")
abline(mod5, col="blue")
text(x=2,y=4, "slope = 0.6262")

gamma <- 5/2
kmeanTher <- ((gamma-1)/(gamma-2))*N^((2-gamma)/(gamma-1))
mod6 <- lm(log10(kmeanTher)~log10(N)) 
plot(y=log10(kmeanTher), x=log10(N), main="K_max theoretical by N", xlab = "log10((k_max))", ylab = "log10(N)")
abline(mod6, col="red")
text(x=3,y=.3, "slope = -0.3333")
par(mfrow=c(1,1))
```
